Fix mypy by ignoring that pytest_mock does not provide type stubs
tox-dev/pyproject-fmt pull request #145
Opened 2023-10-30 21:45 UTC by adamtheturtle

Without this, `mypy src/ tests/` fails.

2023-10-30 22:12 UTC, gaborbernat requested changes

2023-10-30 22:12 UTC, gaborbernat commented on pyproject.toml
> +
inline this configuration please,  as shown here https://github.com/tox-dev/tox/blob/main/pyproject.toml#L163

2023-10-31 07:18 UTC, adamtheturtle commented
If/when https://github.com/pytest-dev/pytest-mock/pull/395 gets shipped, this will not be necessary.

2023-10-31 11:52 UTC, adamtheturtle commented
I think there was an error with my Python setup.

2023-10-31 11:52 UTC, closed without merging