Sort classifiers and respect `--indent`
tox-dev/pyproject-fmt pull request #84
Opened 2023-04-04 15:55 UTC by hugovk

Right now, pyproject-fmt indents most sections using the `--indent` value (default: 2 spaces), but not the project `classifiers` section.

For example, if I first modify this project's `pyproject.toml` to use four space, then run `pyproject-fmt pyproject.toml`, they're all fixed to two spaces, except for the classifiers:

```diff
--- pyproject.toml

+++ pyproject.toml

@@ -1,8 +1,8 @@

 [build-system]
 build-backend = "hatchling.build"
 requires = [
-    "hatch-vcs>=0.3",
-    "hatchling>=1.13",
+  "hatch-vcs>=0.3",
+  "hatchling>=1.13",
 ]

 [project]
@@ -10,8 +10,8 @@

 description = "Format your pyproject.toml file"
 readme = "README.md"
 keywords = [
-    "format",
-    "pyproject",
+  "format",
+  "pyproject",
 ]
 license.file = "LICENSE.txt"
 authors = [{ name = "Bernat Gabor", email = "gaborjbernat@gmail.com" }]
@@ -28,25 +28,25 @@

     "Programming Language :: Python :: 3.11",
 ]
 dynamic = [
-    "version",
+  "version",
 ]
 dependencies = [
-    "packaging>=23",
-    "tomlkit>=0.11.6",
-    'typing-extensions>=4.5; python_version < "3.8"',
+  "packaging>=23",
+  "tomlkit>=0.11.6",
+  'typing-extensions>=4.5; python_version < "3.8"',
 ]
 optional-dependencies.docs = [
-    "furo>=2022.12.7",
-    "sphinx>=6.1.3",
-    "sphinx-argparse-cli>=1.11",
-    "sphinx-autodoc-typehints!=1.23.4,>=1.22",
-    "sphinx-copybutton>=0.5.1",
+  "furo>=2022.12.7",
+  "sphinx>=6.1.3",
+  "sphinx-argparse-cli>=1.11",
+  "sphinx-autodoc-typehints!=1.23.4,>=1.22",
+  "sphinx-copybutton>=0.5.1",
 ]
 optional-dependencies.test = [
-    "covdefaults>=2.3",
-    "pytest>=7.2.2",
-    "pytest-cov>=4",
-    "pytest-mock>=3.10",
+  "covdefaults>=2.3",
+  "pytest>=7.2.2",
+  "pytest-cov>=4",
+  "pytest-mock>=3.10",
 ]
 urls."Bug Tracker" = "https://github.com/tox-dev/pyproject-fmt/issues"
 urls."Changelog" = "https://github.com/tox-dev/pyproject-fmt/releases"
```

With this PR, the classifiers are also sorted and indented:

```diff
--- pyproject.toml

+++ pyproject.toml

@@ -1,8 +1,8 @@

 [build-system]
 build-backend = "hatchling.build"
 requires = [
-    "hatch-vcs>=0.3",
-    "hatchling>=1.13",
+  "hatch-vcs>=0.3",
+  "hatchling>=1.13",
 ]

 [project]
@@ -10,44 +10,44 @@

 description = "Format your pyproject.toml file"
 readme = "README.md"
 keywords = [
-    "format",
-    "pyproject",
+  "format",
+  "pyproject",
 ]
 license.file = "LICENSE.txt"
 authors = [{ name = "Bernat Gabor", email = "gaborjbernat@gmail.com" }]
 requires-python = ">=3.7"
 classifiers = [
-    "License :: OSI Approved :: MIT License",
-    "Operating System :: OS Independent",
-    "Programming Language :: Python",
-    "Programming Language :: Python :: 3 :: Only",
-    "Programming Language :: Python :: 3.7",
-    "Programming Language :: Python :: 3.8",
-    "Programming Language :: Python :: 3.9",
-    "Programming Language :: Python :: 3.10",
-    "Programming Language :: Python :: 3.11",
+  "License :: OSI Approved :: MIT License",
+  "Operating System :: OS Independent",
+  "Programming Language :: Python",
+  "Programming Language :: Python :: 3 :: Only",
+  "Programming Language :: Python :: 3.7",
+  "Programming Language :: Python :: 3.8",
+  "Programming Language :: Python :: 3.9",
+  "Programming Language :: Python :: 3.10",
+  "Programming Language :: Python :: 3.11",
 ]
 dynamic = [
-    "version",
+  "version",
 ]
 dependencies = [
-    "natsort",
-    "packaging>=23",
-    "tomlkit>=0.11.6",
-    'typing-extensions>=4.5; python_version < "3.8"',
+  "natsort",
+  "packaging>=23",
+  "tomlkit>=0.11.6",
+  'typing-extensions>=4.5; python_version < "3.8"',
 ]
 optional-dependencies.docs = [
-    "furo>=2022.12.7",
-    "sphinx>=6.1.3",
-    "sphinx-argparse-cli>=1.11",
-    "sphinx-autodoc-typehints!=1.23.4,>=1.22",
-    "sphinx-copybutton>=0.5.1",
+  "furo>=2022.12.7",
+  "sphinx>=6.1.3",
+  "sphinx-argparse-cli>=1.11",
+  "sphinx-autodoc-typehints!=1.23.4,>=1.22",
+  "sphinx-copybutton>=0.5.1",
 ]
 optional-dependencies.test = [
-    "covdefaults>=2.3",
-    "pytest>=7.2.2",
-    "pytest-cov>=4",
-    "pytest-mock>=3.10",
+  "covdefaults>=2.3",
+  "pytest>=7.2.2",
+  "pytest-cov>=4",
+  "pytest-mock>=3.10",
 ]
 urls."Bug Tracker" = "https://github.com/tox-dev/pyproject-fmt/issues"
 urls."Changelog" = "https://github.com/tox-dev/pyproject-fmt/releases"
```

Note we need to use something like https://github.com/SethMMorton/natsort for the classifiers, because they can include version numbers, and the basic `sorted` gives:

```diff
   "Operating System :: OS Independent",
   "Programming Language :: Python",
   "Programming Language :: Python :: 3 :: Only",
+  "Programming Language :: Python :: 3.10",
+  "Programming Language :: Python :: 3.11",
   "Programming Language :: Python :: 3.7",
   "Programming Language :: Python :: 3.8",
   "Programming Language :: Python :: 3.9",
-  "Programming Language :: Python :: 3.10",
-  "Programming Language :: Python :: 3.11",
 ]
```

2023-04-04 15:57 UTC, hugovk commented
mypy error:
```
src/pyproject_fmt/formatter/util.py:102: error: Cannot call function of unknown type  [operator]
Found 1 error in 1 file (checked 11 source files)
```

Line 102 is the second one here:
```python
    sort_method = natsorted if custom_sort == "natsort" else sorted
    for element in sort_method(entries, key=key):
```

What annotation do we need here?

2023-04-04 16:14 UTC, gaborbernat commented on src/pyproject_fmt/formatter/util.py
> +    sort_method = natsorted if custom_sort == "natsort" else sorted
natsorted -> not_sorted

2023-04-04 18:47 UTC, hugovk commented on src/pyproject_fmt/formatter/util.py
> +    sort_method = natsorted if custom_sort == "natsort" else sorted
Like this?

```python
from natsort import natsorted as nat_sorted

...

    sort_method = nat_sorted if custom_sort == "natsort" else sorted
```

2023-04-04 18:47 UTC, hugovk commented on src/pyproject_fmt/formatter/util.py
> +    custom_sort: str | None = None,
How do you mean?

2023-04-19 17:57 UTC, gaborbernat requested changes
Can you fix the type checker and resolve the merge conflict please?

2023-04-19 18:07 UTC, hugovk commented
Merge conflict resolved, I'm not sure about the type checker but will ask someone here at PyCon :)

2023-04-22 03:18 UTC, hugovk commented
Typing fixed with some help :)

![image](https://user-images.githubusercontent.com/1324225/233759185-4e2ff374-096d-4d2a-b911-cc0316191cf1.png)

2023-04-22 05:14 UTC, merged

2023-04-22 05:15 UTC, gaborbernat commented
I'm also at the conference, should meet up tomorrow 😂